### ISSUE TITLE
crash on drill assembly

### ISSUE THREAD

**Issue by wimvanboven** [Raizunne/Redstonic#23]
client crashes on drill assembly (forge-1.7.10-10.13.3.1388)

edit: i'm on 1.4.5 btw

[20:31:38] [Server thread/ERROR] [FML/]: FMLIndexedMessageCodec exception caught
java.lang.NoClassDefFoundError: com/raizunne/redstonic/Gui/GuiDrillModifier
        at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.7.0_79]
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2585) ~[?:1.7.0_79]
        at java.lang.Class.getConstructor0(Class.java:2885) ~[?:1.7.0_79]
        at java.lang.Class.newInstance(Class.java:350) ~[?:1.7.0_79]
        at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:75) ~[FMLIndexedMessageToMessageCodec.class:?]
        at cpw.mods.fml.common.network.FMLIndexedMessageToMessageCodec.decode(FMLIndexedMessageToMessageCodec.java:17) ~[FMLIndexedMessageToMessageCodec.class:?]
        at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: com.raizunne.redstonic.Gui.GuiDrillModifier
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_79]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_79]
        ... 21 more

**Comment by SirWilli** [comment]
Same here, seems to only happen in multiplayer.

**Comment by Raizunne** [comment]
Im fixing this right now and will have a fix in a few hours. Thanks for reporting!
