### ISSUE TITLE
crash with v1.5.1

### ISSUE THREAD

**Issue by 3bodii912** [Raizunne/Redstonic#41]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  LoadingPlugin (Quark-r1.0-57.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 10/27/16 4:21 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/raizu/redstonic/Items/Drill/Drill
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:580)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoClassDefFoundError: com/raizu/redstonic/Items/Drill/Drill
    at com.raizu.redstonic.Redstonic.<clinit>(Redstonic.java:43)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:505)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:549)
    ... 18 more
Caused by: java.lang.ClassNotFoundException: com.raizu.redstonic.Items.Drill.Drill
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 44 more
Caused by: java.lang.NoClassDefFoundError: cofh/api/energy/IEnergyContainerItem
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 46 more
Caused by: java.lang.ClassNotFoundException: cofh.api.energy.IEnergyContainerItem
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 50 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1605274888 bytes (1530 MB) / 2046296064 bytes (1951 MB) up to 2046296064 bytes (1951 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx2048m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.2.2114 23 mods loaded, 23 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2114-universal.jar) 
    UC  Forge{12.18.2.2114} [Minecraft Forge](forge-1.10.2-12.18.2.2114-universal.jar) 
    UC  Quark{r1.0-57} [Quark](Quark-r1.0-57.jar) 
    UC  AutoRegLib{1.0-2} [AutoRegLib](AutoRegLib-1.0-2.jar) 
    UC  dungeontactics{DT-0.10.6} [DungeonTactics](DungeonTactics-1.10.2-0.10.6.jar) 
    UC  endercore{1.10.2-0.4.1.56-beta} [EnderCore](EnderCore-1.10.2-0.4.1.56-beta.jar) 
    UC  JEI{3.12.8.323} [Just Enough Items](jei_1.10.2-3.12.8.323.jar) 
    UC  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UC  EnderIO{1.10.2-3.0.1.120_beta} [Ender IO](EnderIO-1.10.2-3.0.1.120_beta.jar) 
    UC  ezstorage{2.2.5} [EZStorage 2](ezstorage-2.2.5.jar) 
    UC  gravestone{1.5.8} [Gravestone](GraveStone Mod 1.5.8.jar) 
    UC  ironbackpacks{1.10.2-2.2.7} [Iron Backpacks](IronBackpacks-1.10.2-2.2.7.jar) 
    UE  notenoughwands{1.3.7} [Not Enough Wands](notenoughwands-1.10-1.3.7.jar) 
    UC  PersistentBits{1.0.5} [Persistent Bits](PersistentBits-1.10.2-1.0.5.jar) 
    UC  portablecrafting{1.10.2-1.1} [Portable Crafting](PortableCrafting-1.10.2-1.1.jar) 
    UC  reap{1.3.3} [Reap Mod](ReapMod 1.3.3.jar) 
    UE  redstonic{1.5.1} [Redstonic](Redstonic-1.5.1.jar) 
    UC  simpleoregen{2.0} [Simple Ore Generation](SimpleOreGeneration v2.0 mc1.10.2.jar) 
    UC  spartanshields{1.0} [Spartan Shields](SpartanShields-1.10.2-1.0.jar) 
    UC  VTweaks{1.4.9.6} [V-Tweaks](VTweaks-1.10.x-1.4.9.6.jar) 
    UC  icse{1.1.0.0} [I Can See Everything](Wawla-1.10.2-2.3.0.206.jar) 
    UC  wawla{2.3.0.202} [What Are We Looking At](Wawla-1.10.2-2.3.0.206.jar) 
    Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (Quark-r1.0-57.jar)
  vazkii.quark.base.asm.ClassTransformer
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.0' Renderer: 'AMD Radeon(TM) R4 Graphics'

**Comment by Raizunne** [comment]
Does this happen everytime you start minecraft?

**Comment by 3bodii912** [comment]
yes, but i remove this UE notenoughwands{1.3.7} Not Enough Wands and it works
but now give me this when i try to make a sword :

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  LoadingPlugin (Quark-r1.0-57.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 10/27/16 4:52 AM
Description: Rendering screen

java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays
	at com.raizu.redstonic.Blocks.Modifier.GUIModifier.func_146979_b(GUIModifier.java:67)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.ClassNotFoundException: scala.actors.threadpool.Arrays
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.raizu.redstonic.Blocks.Modifier.GUIModifier.func_146979_b(GUIModifier.java:67)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:114)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: com.raizu.redstonic.Blocks.Modifier.GUIModifier
	Mouse location: Scaled: (295, 177). Absolute: (590, 412)
	Screen size: Scaled: (683, 384). Absolute: (1366, 768). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['3bodiii912'/0, l='MpServer', x=-1240.17, y=56.00, z=-718.20]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-1232,4,-711), Chunk: (at 0,0,9 in -77,-45; contains blocks -1232,0,-720 to -1217,255,-705), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513)
	Level time: 10889 game time, 10889 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['3bodiii912'/0, l='MpServer', x=-1240.17, y=56.00, z=-718.20]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 999834896 bytes (953 MB) / 2080899072 bytes (1984 MB) up to 2080899072 bytes (1984 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx2048m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2114 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2114-universal.jar) 
	UCHIJAAAA	Forge{12.18.2.2114} [Minecraft Forge] (forge-1.10.2-12.18.2.2114-universal.jar) 
	UCHIJAAAA	Quark{r1.0-57} [Quark] (Quark-r1.0-57.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	dungeontactics{DT-0.10.6} [DungeonTactics] (DungeonTactics-1.10.2-0.10.6.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.56-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.56-beta.jar) 
	UCHIJAAAA	JEI{3.12.8.323} [Just Enough Items] (jei_1.10.2-3.12.8.323.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.120_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.120_beta.jar) 
	UCHIJAAAA	ezstorage{2.2.5} [EZStorage 2] (ezstorage-2.2.5.jar) 
	UCHIJAAAA	gravestone{1.5.8} [Gravestone] (GraveStone Mod 1.5.8.jar) 
	UCHIJAAAA	ironbackpacks{1.10.2-2.2.7} [Iron Backpacks] (IronBackpacks-1.10.2-2.2.7.jar) 
	UCHIJAAAA	PersistentBits{1.0.5} [Persistent Bits] (PersistentBits-1.10.2-1.0.5.jar) 
	UCHIJAAAA	portablecrafting{1.10.2-1.1} [Portable Crafting] (PortableCrafting-1.10.2-1.1.jar) 
	UCHIJAAAA	reap{1.3.3} [Reap Mod] (ReapMod 1.3.3.jar) 
	UCHIJAAAA	redstonic{1.5.1} [Redstonic] (Redstonic-1.5.1.jar) 
	UCHIJAAAA	simpleoregen{2.0} [Simple Ore Generation] (SimpleOreGeneration v2.0 mc1.10.2.jar) 
	UCHIJAAAA	spartanshields{1.0} [Spartan Shields] (SpartanShields-1.10.2-1.0.jar) 
	UCHIJAAAA	VTweaks{1.4.9.6} [V-Tweaks] (VTweaks-1.10.x-1.4.9.6.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
	UCHIJAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (Quark-r1.0-57.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.0' Renderer: 'AMD Radeon(TM) R4 Graphics'
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Abdullah%20Muhammed/Desktop/MultiMC/instances/1.10.2/minecraft/mods/Redstonic-1.5.1.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: AMD Radeon(TM) R4 Graphics GL version 4.5.13399 Compatibility Profile Context 15.201.1101.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A6-6310 APU with AMD Radeon R4 Graphics

**Comment by Raizunne** [comment]
Alright I'll try to work out the first but, the second one should be fixed in 1.5.2 in about 30 min. Thanks for reporting!

**Comment by Raizunne** [comment]
This version is no longer supported, update to v2
