### ISSUE TITLE
Crash with AE2 Spactial

### ISSUE THREAD

**Issue by monokin** [Raizunne/Redstonic#6]
Im not exactly sure whos fault this is but I crash when I enter Spactial and the only thing that shows up is

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 3/6/15 2:29 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.raizunne.redstonic.Client.BlockLooking.init(BlockLooking.java:28)
	at com.raizunne.redstonic.Handler.RedstonicEventHandler.RenderGameOverlayEvent(RedstonicEventHandler.java:34)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_646_RedstonicEventHandler_RenderGameOverlayEvent_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:102)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1325)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.raizunne.redstonic.Client.BlockLooking.init(BlockLooking.java:28)
	at com.raizunne.redstonic.Handler.RedstonicEventHandler.RenderGameOverlayEvent(RedstonicEventHandler.java:34)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_646_RedstonicEventHandler_RenderGameOverlayEvent_RenderGameOverlayEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:895)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:102)

**Comment by Raizunne** [comment]
I've fixed this (or atleast that's what I've gotten from testing this) in the new version 1.2.
You can get it here: http://raizunne.github.io/Mods/Redstonic/downloads.html
